### ISSUE TITLE
Namespace collision within PyPI

### ISSUE THREAD

**Issue by krmaxwell** [yolothreat/utilitybelt#21]
So I'm working on the upload to PyPI and got an HTTP 403. Turns out there's already a [package with the same name](https://pypi.python.org/pypi/utilitybelt/0.2.2). 

We will need to rename in some way, either by finding something to prepend ('cnd-utilitybelt'?) or a full-fledged rename.

**Comment by sroberts** [comment]
:metal: Now we need to figure out what we want to update the README with.
