### ISSUE TITLE
Move to CircleCI

### ISSUE THREAD

**Issue by krmaxwell** [yolothreat/utilitybelt#23]
Why stay on Travis? It isn't working anyway and we both want to centralize on Circle. Thoughts?

**Comment by sroberts** [comment]
100% agreed.

**Comment by krmaxwell** [comment]
Done, see https://circleci.com/gh/yolothreat/utilitybelt and https://travis-ci.org/yolothreat/utilitybelt/

Now to get the tests passing.

**Comment by sroberts** [comment]
:metal: Glad to get this moved over.
