### ISSUE TITLE
Project engineering

### ISSUE THREAD

**Issue by krmaxwell** [yolothreat/utilitybelt#27]
Now that existing tests are passing, we need a few more things:

- [x] Waffle.io board
- [x] Pre-commit setup
- [x] Code coverage testing
- [x] Landscape.io code quality testing
- [x] Stinking badges

**Comment by krmaxwell** [comment]
https://waffle.io/yolothreat/utilitybelt

**Comment by krmaxwell** [comment]
https://coveralls.io/r/yolothreat/utilitybelt
https://landscape.io/github/yolothreat/utilitybelt

**Comment by krmaxwell** [comment]
All of this is in #27 FWIW.

**Comment by sroberts** [comment]
:+1:
