### ISSUE TITLE
Make Maxmind DB Dynamically Pulled

### ISSUE THREAD

**Issue by sroberts** [yolothreat/utilitybelt#34]
I personally hate the idea of including the MaxMind DB in the package itself and I think it would be much better if it was automatically downloaded by the library itself. In addition it'd be great if that check also automatically updated the library if it's sufficiently out of date.

I can be convinced against this, but right now it seems like the better way to me. Thoughts?

**Comment by krmaxwell** [comment]
FTR, this is done in jager now, so you can grab the code from there and re-use.

**Comment by sroberts** [comment]
:Metal:
